[package]
name = "cypher-world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cypher-character = { path = "../cypher-character"}

bevy = { version = "0.8", default-features = false }