[package]
name = "cypher-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cypher-world = { path = "../cypher-world" }

bevy = { version = "0.8" }