[package]
name = "cypher-dungeon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.bevy]
workspace = true
features = ["default"]

[dependencies]
rand = "0"

strum = "0.24"
strum_macros = "0.24"